name: Docker Push

on: push

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Docker Build & Push Frontend to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "ase-frontend"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
          BUILD_PATH: "frontend/"

      - name: Docker Build & Push Backend to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "ase-backend"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
          BUILD_PATH: "backend/"

      - name: Docker Build & Push Sales-api to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "ase-sales-api"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
          BUILD_PATH: "sales-api/"

      - name: Docker Build & Push airbnb-api to Docker Hub
        uses: opspresso/action-docker@master
        with:
          args: --docker
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}
          PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKERFILE: "Dockerfile"
          IMAGE_NAME: "ase-airbnb-api"
          TAG_NAME: "v0.0.1"
          LATEST: "true"
          BUILD_PATH: "airbnb-api/"